name: Test Build

# on: 
#   pull_request:
on:
  push:

jobs:

  flatpak-builder:
    name: Flatpak Builder
    # runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
   
    strategy:
      fail-fast: true
      matrix:
        variant:
          # - arch: x86_64
          #   runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.variant.runner }}
    steps:
      - uses: actions/checkout@v4

      # - name: Install docker client
      #   if: ${{ matrix.variant.arch != 'aarch64' }}
      #   run: |
      #     # Use the static binaries because it's unable to use a package manager 
      #     curl https://download.docker.com/linux/static/stable/x86_64/docker-26.0.0.tgz --output ./docker.tgz
      #     tar xzvf docker.tgz
      #     mv docker/* /usr/bin
      # - name: Set up QEMU
      #   if: ${{ matrix.variant.arch != 'aarch64' }}
      #   uses: docker/setup-qemu-action@v3
      #   with:
      #     platforms: linux/aarch64
      
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          architecture: 'arm64'
          verbose: true

      - name: Install Deps
        run: |
          # flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          # flatpak install flathub org.freedesktop.Platform/aarch64/25.08 org.freedesktop.Sdk/aarch64/25.08 -y
          corepack enable
          corepack prepare yarn@stable --activate
          yarn install --immutable
          # chmod u+s /usr/bin/bwrap

      # - name: Build Electron App
      #   run: |
      #     echo "c3e06eb9bf1c4392b834a89c95f82870" > /etc/machine-id
      #     export DEBUG="@malept/flatpak-bundler"
      #     yarn run app:dirarm
        

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6.6
        with:
          arch: aarch64
          bundle: slacky.flatpak
          manifest-path: flatpak-manifest.yml
          verbose: true
          upload_artifact: false 
          # cache-key: flatpak-builder-${{ github.sha }}
          
      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v4
        with:
          name: slacky-flatpak-pr-${{ github.event.number }}
          path: slacky.flatpak